import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import nodemailer from "nodemailer";

import { pool } from "./postgres.js";

const OUTBOX_DIR = join(process.cwd(), "data", "email_outbox");
const COMPANY_NAME = "Njinko Development Group LLC";
const DEFAULT_APP_URL = "https://investors.njinkofarm.com/";

function nowTimestamp() {
  return new Date().toISOString();
}

function createNotificationId() {
  return `email-${randomUUID()}`;
}

function normalizeConfigValue(value) {
  return String(value ?? "")
    .trim()
    .replace(/\s+#.*$/, "")
    .trim();
}

function resolveLoginUrl() {
  const explicit = normalizeConfigValue(process.env.APP_URL);

  if (explicit) {
    return explicit;
  }

  return DEFAULT_APP_URL;
}

function buildCredentialBody({ fullName, email, temporaryPassword, role }) {
  return [
    `Hello ${fullName},`,
    "",
    `A new ${COMPANY_NAME} portal account has been created for you.`,
    "",
    `Role: ${role}`,
    `Login URL: ${resolveLoginUrl()}`,
    `Email: ${email}`,
    `Temporary password: ${temporaryPassword}`,
    "",
    "For security, you will be required to change your password the first time you log in.",
    "",
    `If you were not expecting this message, please contact ${COMPANY_NAME}.`
  ].join("\n");
}

function buildIssueCreatedBody({
  fullName,
  dealName,
  issueTitle,
  issueDescription,
  approvalThreshold,
  closesOn,
  weightPct
}) {
  return [
    `Hello ${fullName},`,
    "",
    `A new investor voting issue has been opened for ${dealName}.`,
    "",
    `Issue: ${issueTitle}`,
    `Approval required: ${Math.round(approvalThreshold * 100)}%`,
    `Your voting weight: ${Math.round(weightPct * 1000) / 10}%`,
    `Vote closes: ${closesOn || "Open ended"}`,
    "",
    "Issue details:",
    issueDescription,
    "",
    `Log in to review and vote: ${resolveLoginUrl()}`,
    "",
    `If you have questions, contact ${COMPANY_NAME}.`
  ].join("\n");
}

function buildNewDealAnnouncementBody({
  fullName,
  dealName,
  location,
  currentPhase,
  investmentCloseOn
}) {
  return [
    `Hello ${fullName},`,
    "",
    `A new project, ${dealName}, is now available in the ${COMPANY_NAME} portal.`,
    "",
    `Location: ${location}`,
    `Current phase: ${currentPhase}`,
    `Investment window closes: ${investmentCloseOn || "Not set"}`,
    "",
    "If you have proceeds from a closed project and want to reinvest into this new deal, log in to review the opportunity and update your elections early.",
    "",
    `Portal link: ${resolveLoginUrl()}`,
    "",
    `If you have questions, contact ${COMPANY_NAME}.`
  ].join("\n");
}

function buildPasswordResetBody({ fullName, resetUrl, expiresInMinutes }) {
  return [
    `Hello ${fullName},`,
    "",
    `A password reset was requested for your ${COMPANY_NAME} portal account.`,
    "",
    `Reset your password: ${resetUrl}`,
    `This link expires in ${expiresInMinutes} minutes and can only be used once.`,
    "",
    "If you did not request a password reset, you can ignore this message.",
    "",
    `If you need help, contact ${COMPANY_NAME}.`
  ].join("\n");
}

function buildDistributionElectionAlertBody({
  managerName,
  investorName,
  dealName,
  electionMode,
  cashPayoutAmount,
  reinvestAmount,
  rolloverTargetDealName,
  notes,
  submittedAt
}) {
  const modeLabels = {
    payout_all: "Cash out all proceeds",
    reinvest_all: "Reinvest all proceeds",
    split_percentage: "Split by percentage",
    split_amount: "Split by fixed amount"
  };

  return [
    `Hello ${managerName},`,
    "",
    `${investorName} submitted a distribution election for ${dealName}.`,
    "",
    `Instruction: ${modeLabels[electionMode] ?? electionMode}`,
    `Cash payout amount: $${Number(cashPayoutAmount ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })}`,
    `Reinvested amount: $${Number(reinvestAmount ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })}`,
    `Rollover target: ${rolloverTargetDealName || "No target selected"}`,
    `Submitted at: ${submittedAt}`,
    "",
    notes ? `Investor notes: ${notes}` : "Investor notes: None provided.",
    "",
    `Review or override the election in the manager portal: ${resolveLoginUrl()}`,
    "",
    `This notice was generated by ${COMPANY_NAME}.`
  ].join("\n");
}

function payoutMethodLabel(method) {
  const labels = {
    bank: "Bank account",
    zelle: "Zelle",
    cash_app: "Cash App",
    other: "Other instructions"
  };

  return labels[String(method ?? "").trim()] ?? "Saved payout instructions";
}

function buildDistributionElectionApprovedBody({
  fullName,
  dealName,
  electionMode,
  approvedAt,
  payoutExpectedOn,
  payoutMethod,
  cashPayoutAmount,
  reinvestAmount,
  rolloverTargetDealName,
  managerOverride,
  overrideNotes,
  notes
}) {
  const modeLabels = {
    payout_all: "Cash out all proceeds",
    reinvest_all: "Reinvest all proceeds",
    split_percentage: "Split by percentage",
    split_amount: "Split by fixed amount"
  };

  return [
    `Hello ${fullName},`,
    "",
    `Your reinvestment or payout election for ${dealName} has been approved.`,
    "",
    `Approved at: ${approvedAt}`,
    `Final instruction: ${modeLabels[electionMode] ?? electionMode}`,
    `Approved cash payout: $${Number(cashPayoutAmount ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })}`,
    `Approved reinvestment: $${Number(reinvestAmount ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })}`,
    `Reinvestment target: ${rolloverTargetDealName || "No target selected"}`,
    `Payout method: ${payoutMethodLabel(payoutMethod)}`,
    `Expected payout date: ${payoutExpectedOn || "No cash payout scheduled"}`,
    "",
    notes ? `Submitted notes: ${notes}` : "Submitted notes: None provided.",
    managerOverride && overrideNotes
      ? `Manager override notes: ${overrideNotes}`
      : managerOverride
        ? "Manager override notes: The manager approved a revised distribution instruction."
        : "Manager override notes: None.",
    "",
    `Log in to review the approved distribution plan: ${resolveLoginUrl()}`,
    "",
    `This notice was generated by ${COMPANY_NAME}.`
  ].join("\n");
}

function getSmtpConfig() {
  const host = normalizeConfigValue(process.env.SMTP_HOST);
  const user = normalizeConfigValue(process.env.SMTP_USER);
  const pass = normalizeConfigValue(process.env.SMTP_PASS);

  if (!host || !user || !pass) {
    return null;
  }

  const port = Number(normalizeConfigValue(process.env.SMTP_PORT) || 465);
  const secureValue = normalizeConfigValue(process.env.SMTP_SECURE).toLowerCase();
  const secure = secureValue ? secureValue === "true" : port === 465;

  return {
    host,
    port,
    secure,
    auth: {
      user,
      pass
    },
    from:
      normalizeConfigValue(process.env.SMTP_FROM) ||
      normalizeConfigValue(process.env.EMAIL_FROM) ||
      user
  };
}

async function saveLocalOutbox(notificationId, payload, errorMessage = null) {
  await mkdir(OUTBOX_DIR, { recursive: true });

  const fileName = `${notificationId}.json`;
  const absolutePath = join(OUTBOX_DIR, fileName);
  const localPath = `data/email_outbox/${fileName}`;

  await writeFile(
    absolutePath,
    JSON.stringify(
      {
        ...payload,
        createdAt: nowTimestamp(),
        errorMessage
      },
      null,
      2
    )
  );

  return {
    status: "saved_local",
    provider: "local_outbox",
    localPath,
    sentAt: nowTimestamp(),
    errorMessage
  };
}

async function deliverWithResend(payload) {
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      from: process.env.EMAIL_FROM,
      to: [payload.recipientEmail],
      subject: payload.subject,
      text: payload.bodyText
    })
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(detail || `Resend request failed with status ${response.status}.`);
  }

  return {
    status: "sent",
    provider: "resend",
    localPath: null,
    sentAt: nowTimestamp(),
    errorMessage: null
  };
}

async function deliverWithSmtp(payload) {
  const smtp = getSmtpConfig();

  if (!smtp) {
    throw new Error("SMTP is not fully configured.");
  }

  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.secure,
    connectionTimeout: 10000,
    greetingTimeout: 10000,
    socketTimeout: 10000,
    auth: smtp.auth
  });

  await transporter.sendMail({
    from: smtp.from,
    to: payload.recipientEmail,
    subject: payload.subject,
    text: payload.bodyText
  });

  return {
    status: "sent",
    provider: "smtp",
    localPath: null,
    sentAt: nowTimestamp(),
    errorMessage: null
  };
}

async function deliverNotification(notificationId, payload) {
  if (getSmtpConfig()) {
    try {
      return await deliverWithSmtp(payload);
    } catch (error) {
      return saveLocalOutbox(notificationId, payload, `SMTP fallback: ${error.message}`);
    }
  }

  if (process.env.RESEND_API_KEY && process.env.EMAIL_FROM) {
    try {
      return await deliverWithResend(payload);
    } catch (error) {
      return saveLocalOutbox(notificationId, payload, `Resend fallback: ${error.message}`);
    }
  }

  return saveLocalOutbox(notificationId, payload);
}

async function queueAndDeliverNotification({
  userId,
  participantId,
  recipientEmail,
  subject,
  bodyText,
  persist = true
}) {
  const notificationId = createNotificationId();
  const payload = {
    recipientEmail,
    subject,
    bodyText
  };
  const createdAt = nowTimestamp();

  if (persist) {
    await pool.query(
      `
        INSERT INTO email_notifications (
          id,
          user_id,
          participant_id,
          recipient_email,
          subject,
          body_text,
          status,
          provider,
          created_at
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `,
      [
        notificationId,
        userId,
        participantId,
        payload.recipientEmail,
        payload.subject,
        payload.bodyText,
        "queued",
        "pending",
        createdAt
      ]
    );
  }

  const delivery = await deliverNotification(notificationId, payload);

  if (persist) {
    await pool.query(
      `
        UPDATE email_notifications
        SET
          status = $1,
          provider = $2,
          local_path = $3,
          error_message = $4,
          sent_at = $5
        WHERE id = $6
      `,
      [
        delivery.status,
        delivery.provider,
        delivery.localPath,
        delivery.errorMessage,
        delivery.sentAt,
        notificationId
      ]
    );
  }

  return {
    id: notificationId,
    ...delivery
  };
}

export async function sendCredentialNotification({
  userId,
  participantId,
  fullName,
  email,
  role,
  temporaryPassword
}) {
  const payload = {
    recipientEmail: email,
    subject: `${COMPANY_NAME} portal login`,
    bodyText: buildCredentialBody({
      fullName,
      email,
      temporaryPassword,
      role
    })
  };
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: payload.recipientEmail,
    subject: payload.subject,
    bodyText: payload.bodyText,
    persist: true
  });
}

export async function sendIssueCreatedNotification({
  userId,
  participantId,
  fullName,
  email,
  dealName,
  issueTitle,
  issueDescription,
  approvalThreshold,
  closesOn,
  weightPct
}) {
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: email,
    subject: `New investor vote for ${dealName}`,
    bodyText: buildIssueCreatedBody({
      fullName,
      dealName,
      issueTitle,
      issueDescription,
      approvalThreshold,
      closesOn,
      weightPct
    }),
    persist: false
  });
}

export async function sendPasswordResetNotification({
  userId,
  participantId,
  fullName,
  email,
  resetUrl,
  expiresInMinutes
}) {
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: email,
    subject: `${COMPANY_NAME} password reset`,
    bodyText: buildPasswordResetBody({
      fullName,
      resetUrl,
      expiresInMinutes
    }),
    persist: false
  });
}

export async function sendNewDealAnnouncementNotification({
  userId,
  participantId,
  fullName,
  email,
  dealName,
  location,
  currentPhase,
  investmentCloseOn
}) {
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: email,
    subject: `New project available: ${dealName}`,
    bodyText: buildNewDealAnnouncementBody({
      fullName,
      dealName,
      location,
      currentPhase,
      investmentCloseOn
    }),
    persist: false
  });
}

export async function sendDistributionElectionAlertNotification({
  userId,
  participantId,
  managerName,
  email,
  investorName,
  dealName,
  electionMode,
  cashPayoutAmount,
  reinvestAmount,
  rolloverTargetDealName,
  notes,
  submittedAt
}) {
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: email,
    subject: `Investor distribution election submitted for ${dealName}`,
    bodyText: buildDistributionElectionAlertBody({
      managerName,
      investorName,
      dealName,
      electionMode,
      cashPayoutAmount,
      reinvestAmount,
      rolloverTargetDealName,
      notes,
      submittedAt
    }),
    persist: false
  });
}

export async function sendDistributionElectionApprovedNotification({
  userId,
  participantId,
  fullName,
  email,
  dealName,
  electionMode,
  approvedAt,
  payoutExpectedOn,
  payoutMethod,
  cashPayoutAmount,
  reinvestAmount,
  rolloverTargetDealName,
  managerOverride,
  overrideNotes,
  notes
}) {
  return queueAndDeliverNotification({
    userId,
    participantId,
    recipientEmail: email,
    subject: `Distribution election approved for ${dealName}`,
    bodyText: buildDistributionElectionApprovedBody({
      fullName,
      dealName,
      electionMode,
      approvedAt,
      payoutExpectedOn,
      payoutMethod,
      cashPayoutAmount,
      reinvestAmount,
      rolloverTargetDealName,
      managerOverride,
      overrideNotes,
      notes
    }),
    persist: false
  });
}
